version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"   # adjust if your package.json is not in the root
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        dependency-name: "@medusajs/js-sdk"
      - dependency-type: "all"
        dependency-name: "@medusajs/types"